language: java

branches:
  except:
      #- /^(?i:feature)-.*$/
      #- /^(?i:release)-.*$/

jdk:
  - oraclejdk8

install:
    - mvn --settings .travis/settings.xml install -DskipTests=true -Dmaven.javadoc.skip=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B -U -V -q

before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

notifications:
    email:
        on_success: never
        on_failure: never
    slack:
        on_failure: change
        on_success: change
        rooms:
            - openbase-org:vGz7LO4CvGoGMneYkEm3ON7E#build
            #- openbase-org:vGz7LO4CvGoGMneYkEm3ON7E#bco-manager

deploy:
  - provider: script
    skip_cleanup: true
    script: .travis/deploy.sh
    on:
        repo: openbase/bco.manager
        branch: master
        jdk: oraclejdk8
  - provider: script
    skip_cleanup: true
    script: .travis/deploy.sh
    on:
        repo: openbase/bco.manager
        tags: true
        jdk: oraclejdk8
        
after_deploy:
   - |
       if [[ ($TRAVIS_BRANCH == master) &&
             ($TRAVIS_PULL_REQUEST == false) &&
             ( (! $TRAVIS_JOB_NUMBER == *.*) || ($TRAVIS_JOB_NUMBER == *.1) ) ]] ; then
         curl -LO https://raw.github.com/mernst/plume-lib/master/bin/trigger-travis.sh

         # trigger upstream projects
         # sh trigger-travis.sh openbase bco.bcozy $TRAVIS_ACCESS_TOKEN
       fi
