language: java

dist: xenial

jdk:
  - openjdk8
  - openjdk11
  - openjdk-ea

install:
  - mvn --settings .travis/settings.xml install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -q

before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

notifications:
    email:
        on_success: never
        on_failure: never
    slack:
        on_failure: change
        on_success: change
        rooms:
            - openbase-org:vGz7LO4CvGoGMneYkEm3ON7E#build
            #- openbase-org:vGz7LO4CvGoGMneYkEm3ON7E#bco-registry

deploy:
  - provider: script
    script: .travis/deploy.sh
    on:
        repo: openbase/bco.registry
        branch: master
        jdk: openjdk11
  - provider: script
    script: .travis/deploy.sh
    on:
        repo: openbase/bco.registry
        tags: true
        jdk: openjdk11

jobs:
  include:
    - stage: trigger downstream
      jdk: openjdk11
      script: |
        echo "TRAVIS_BRANCH=$TRAVIS_BRANCH TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
        if [[ ($TRAVIS_BRANCH == master) &&
              ($TRAVIS_PULL_REQUEST == false) ]] ; then
          curl -LO --retry 3 https://raw.github.com/mernst/plume-lib/master/bin/trigger-travis.sh

          # trigger upstream projects
          sh trigger-travis.sh openbase bco.dal $TRAVIS_ACCESS_TOKEN
          sh trigger-travis.sh openbase bco.registry.editor $TRAVIS_ACCESS_TOKEN
        fi
